---
name: "sparc2-plugin-sidebar"
controllers:
  - SPARCControllerSidebar.js
directives:
  - sparcSidebar.js
  - sparcSidebarFeatureLayer.js
  - sparcModalFilterMore.js
  - sparcFilterCheckbox.js
  - sparcFilterRadio.js
  - sparcFilterSlider.js
templates:
  - sparc_sidebar.tpl.html
  - sparc_sidebar_featurelayer.tpl.html
  - modal/modal_filter_more.tpl.html
  - filter/filter_checkbox.tpl.html
  - filter/filter_radio.tpl.html
  - filter/filter_slider.tpl.html
less:
  - sidebar.less
  - sidebar-toggle.less
  - filter.less
