---
controllers:
  - SPARCControllerSidebar.js
directives:
  - sparcSidebar.js
  - sparcSidebarFeatureLayer.js
templates:
  - sparc_sidebar.tpl.html
  - sparc_sidebar_featurelayer.tpl.html
less:
  - sidebar.less
  - sidebar-toggle.less
